import { FeaturedProjectsSectionType } from '@/lib/types/sections';
import { getId } from '@/lib/utils/helper';

const featuredProjectsSection: FeaturedProjectsSectionType = {
  title: "projects i've worked on",
  projects: [
    {
      id: getId(),
      name: 'HIMS (Hospital Information Management System)',
      description: 'A comprehensive Hospital Information Management System developed using MERN technologies.',
      tasks: 'Developed the HIMS project using MERN technologies, encompassing both front-end and back-end development. Implemented modules for appointments, insurance, financial reporting, access configuration, employees, OPD, IPD, pathology, radiology, pharmacy, and blood bank management. Ensured seamless user experience and efficient data handling by integrating robust APIs and optimizing database performance. ',
      url: 'https://pakhims.com',
      img: '/portfolio/hims.png',
      tags: [
        // 'JavaScript Frameworks',
        'SQL',
        'Express.js',
        'Docker',
        'Typescript',
        'Nest.js',
        'GitHub',
        // 'Access Control',
        // 'Cloud Infrastructure',
        // 'Cloud Services',
        // 'Project Management',
        // 'MVP',
        'ERP System',
        'SQLite',
        // 'Heroku',
        'Cloudflare',
        'Node.js',
        'MongoDB',
        'REST API',
        'React.js',
        'Microservices',
        // 'TCP',
        'Swagger',
      ],
    },
    {
      id: getId(),
      name: 'Cyara/TestRTC',
      description: 'A comprehensive platform utilizing WebRTC for real-time communication, developed with full-stack technologies.',
      tasks: 'Developed the TestRTC project utilizing Express.js with Typescript, React.js, MongoDB, WebRTC, AWS, and Lambda Functions. Created a robust backend using Express.js, ensuring type safety and efficient server-side operations. Implemented a dynamic frontend with React.js to provide a seamless user interface and interactive user experience. Utilized MongoDB for efficient, scalable database management, handling large volumes of real-time data. ',
      url: 'https://videotest.testrtc.com',
      img: '/portfolio/cyara.png',
      tags: [
        'Node.js',
        'MongoDB',
        'Express.js',
        'AWS S3',
        'AWS EC2',
        'Microsoft Azure',
        'Docker',
        'Next.js',
        'SQL Server',
        'Typescript',
        'Nest.js',
        'Memcached',
        'ElasticSearch',
        'Lambda Functions',
        'React.js',
        'Google Extensions',
      ],
    },
    {
      id: getId(),
      name: 'Fujairah HR – UAE Government',
      description: 'Developed an HR system for UAE Government using MERN stack with WebSockets for real-time communication.',
      tasks: 'Developed Fujairah HR project from scratch using React, MongoDB, Node.js, Express.js, and Websockets within MERN technologies. Implemented full-stack development, covering both frontend and backend. Enabled real-time communication with Websockets to enhance user experience and system responsiveness. Optimized data storage and retrieval functionalities using MongoDB for better performance. Implemented secure authentication and authorization mechanisms to protect sensitive government data. Collaborated with stakeholders to ensure technical solutions aligned with business objectives and user requirements. Maintained high code quality through rigorous testing and adherence to best practices.',
      url: 'https://fuj-hr.ae',
      img: '/portfolio/fujairah.png',
      tags: [
        'MongoDB',
        'Mongoose',
        'Express.js',
        'Nest.js',
        'Microservices',
        'TCP',
        'Azure Deployment',
        'Cloud Services',
        'Third-party APIs',
        'Swagger',
        'Firebase',
        'Stripe Integration',
        'GitHub',
      ],
    },
    {
      id: getId(),
      name: 'GotStuck Mobile Application (Recovery / Car Transportation)',
      description: 'A mobile platform connecting service providers with motorists for vehicle recovery and transportation.',
      tasks: 'Developed GotStuck, a platform connecting service providers with motorists and traders for vehicle recovery and transportation, using MERN and Flutter. Implemented Geo-location and live activity tracking for efficient service provider connections. Created a user-friendly app for swift booking, reducing response time and costs. Built a complete backend using MongoDB, Express.js, React.js, and Node.js. Developed a Flutter-based mobile app for Android and iOS compatibility. Integrated secure payment gateways (PayPal, Stripe) for smooth online transactions.',
      url: 'https://gotstuck.co.uk',
      img: '/portfolio/got.png',
      tags: [
        'MongoDB',
        'Mongoose',
        'Express.js',
        'Nest.js',
        'Microservices',
        'TCP',
        'Azure Deployment',
        'Cloud Services',
        'Third-party APIs',
        'Swagger',
        'Firebase',
        'Stripe Integration',
      ],
    },
]

  
};

export default featuredProjectsSection;
